name: Node.js Package Publish (Utilities)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-utilities-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
           cd packages/utilities
           npm install
           npm run-script build
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
