name: Node.js Package Publish (Auth)

on:
  workflow_dispatch:

jobs:
  publish-utilities-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v16
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
           cd packages/auth
           npm install
           npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
